### ISSUE TITLE
I can't download manga from https://hentai2read.com

### ISSUE THREAD

**Issue by tienok2004** [manga-py/manga-py#324]
# Bug report
Environment (please complete the following information):

I cannot download any manga from hentai2read.com.
Can you consider this error?
Your software is awesome. If I can donate to you, which channels can I donate?

Thanks

Description | Data
---|---
OS | Windown 10
Python version | 3.8.5
Pip version | 20.1.1
Manga-py version | 1.19.13
URL | https://hentai2read.com/seeing_her_panties_lets_me_stick_in/

**Comment by 1271** [comment]
Thanks for your words.

Fix will be in the next update.

Donate means ongoing support. I cannot guarantee you this.
But if it is from a pure heart, then https://paypal.me/sttvpc

**Comment by 1271** [comment]
Done. Check updates. (docker images building in progress)
Anyway, thanks for using manga-py

**Comment by tienok2004** [comment]
I still cannot download it even after upgrading to version 1.19.15
https://i.imgur.com/on7GEpu.png

**Comment by 1271** [comment]
Please, run 
```manga-py --version```

**Comment by 1271** [comment]
And for update:
```pip install -U manga-py```

**Comment by tienok2004** [comment]
It's worl. Thanks you so much
